spring:
  datasource:
    url: jdbc:h2:file:./db_file
    username: sa
    password: s0m5c0mpl3xp@ssword
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      path: /h2-console
      enabled: true